/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bdg_double07_reversecshell_instrumentation_reverseshell_NativeReverseShell */

#ifndef _Included_com_bdg_double07_reversecshell_instrumentation_reverseshell_NativeReverseShell
#define _Included_com_bdg_double07_reversecshell_instrumentation_reverseshell_NativeReverseShell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bdg_double07_reversecshell_instrumentation_reverseshell_NativeReverseShell
 * Method:    reverse_shell
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bdg_double07_reversecshell_instrumentation_reverseshell_NativeReverseShell_reverse_1shell
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
